version: '2'

services:

  jenkins:
    image: jenkins:2.3
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home

  consul-server:
    container_name: consul
    image: consul
    network_mode: host
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -bind=$HOST_IP -bootstrap-expect=1 -client=$HOST_IP

  registrator:
    container_name: registrator
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip $HOST_IP consul://$CONSUL_IP:8500
